### PR TITLE
Allow configuring Anti-captcha timeout

### PR DESCRIPTION
**Pull request by eugenesia**
During busy periods, the Anti-captcha timeout of 60s is insufficient. Set the default to 180s and allow user to configure it in the `configFile.cfg`.

### CODE REVIEW

**Comment by ad-m** [comment]
I think - if there is a problem - the default settings should be changed instead of giving everyone a choice.

**Comment by igbt6** [comment]
As ad-m said, I think the better idea is to modify the default parameter: timeout_time_sec = 60  # timeout  to 120 or 180 in https://github.com/igbt6/Packt-Publishing-Free-Learning/blob/master/src/utils/anticaptcha.py  file

**Comment by mjenczmyk** [comment]
I think that modifying the source code isn't the best idea. What if somebody wants to install that script into virtualenv? What if I update the source code on my VPS with `git pull` - it's possible I'll have to resolve the conflict than. It seems to me that it's inconvenient.

I agree that the timeout should be configurable (or at least increased).

**Comment by mjenczmyk** [comment]
By the way - I also had to increase the timeout in the source code today or the script wouldn't succeed.

**Comment by eugenesia** [comment]
Hi everyone I reorganised some of my code branches so this merge request was automatically closed. Please refer to the new request #83 which is a continuation of this.

I've taken your feedback into account and just increased the default Anti-captcha timeout to 180s, instead of adding a config parameter.

**Pull request closed without merging**
