### PR TITLE
Save grabbed book informations to file

### PR DESCRIPTION
**Pull request by brunifrancesco**
After grabbing book, save informations (title/author/date) to log file. 
Example in the README.
A new option has been added.

### CODE REVIEW

**Comment by nevzat** [comment]
how about an extra parameter for exporting all book meta-data to html, xml and/or csv, even xls and Google Sheets files?
isbn, book title, release/buy date, file size, file type etc. in a clean format would be great for knowing about our Packt e-book archive.

**Comment by brunifrancesco** [comment]
All books in user library? Or as you grab free books it writes infos to log file?
Should you declare multiple log files in the configs?
I think file size/type infos are not relevant to be logged up.

**Comment by nevzat** [comment]
I think logging should be about the operations the Python code did. 
What I'd like to see is maybe another option/switch for exporting all books meta-data to a file

**Comment by brunifrancesco** [comment]
Ok, good.
So, I'd say to implement this new job and edit what I did to select export format.
So wait for the next PR.
It's up to you to merge this one or reject it. 

bye

**Comment by nevzat** [comment]
Thanks bruni. I'm a newby in Github and Python, just learning right now.
@igbt6 might accept/merge the changes as he's the owner of this Python project.
I'm gonna contribute as soon as I learn Python enough.

**Comment by igbt6** [comment]
Hi @brunifrancesco , thanks for some nice lokking patches, i'll merge all those changes till 8ec8cac8653e4ba45333890dbad41e228055ce88 commit, It would be good if could follow the camelCase letter while naming methods, or, i'll fix it on my own later!

**Comment by igbt6** [comment]
ok done, thanks!

**Pull request closed without merging**
