### PR TITLE
Subdirectory Downloads

### LINKED ISSUE #23: Subdirectorys
Wouldn't it be better to put all files into subdirectorys based on the books name?

### PR DESCRIPTION
**Pull request by iambenzo**
Downloads now get organised into subdirectories based on the ebook title.

Fixes #23

### CODE REVIEW

**Comment by iambenzo** [comment]
If you're unhappy with this PR for any reason, please let me know...it's my first attempt at contributing to someone else's project on GitHub.

**Comment by igbt6** [comment]
Ah sorry! Forgot about it!! When i'll be back at home, i'll tests and of course mege your request, looks ok !

**Comment by igbt6** [comment]
Merged, i have added this option as a new switch "-f"
Btw, thx for whitespaces cleaning ; )

**Comment by iambenzo** [comment]
Great! Thank you for creating this awesome tool :)

**Pull request closed without merging**
