### PR TITLE
anticaptcha: increase timeout

### PR DESCRIPTION
**Pull request by scadu**
Google increased complexity of its Recaptcha and asks to solve more
puzzles, thus increasing average solve time.

### CODE REVIEW

**Comment by scadu** [comment]
Not sure if adding a setting to configuration file wouldn't be better.

**Comment by eugenesia** [comment]
Hi @scadu I've created a merge request #83 which should solve your problem. Does that work for you?

**Comment by igbt6** [comment]
Done at: #83

**Comment by scadu** [comment]
@eugenesia that's great! Thanks.

**Pull request closed without merging**
